/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedHostRouteImport } from './routes/_authenticated/host'
import { Route as AuthenticatedMyGamesRouteImport } from './routes/_authenticated/my-games'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as ActivityIdRouteImport } from './routes/activity.$id'
import { Route as OrganizerIdRouteImport } from './routes/organizer.$id'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicCronMaintenanceRouteImport } from './routes/api/public/cron/maintenance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHostRoute = AuthenticatedHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyGamesRoute = AuthenticatedMyGamesRouteImport.update({
  id: '/my-games',
  path: '/my-games',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ActivityIdRoute = ActivityIdRouteImport.update({
  id: '/activity/$id',
  path: '/activity/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerIdRoute = OrganizerIdRouteImport.update({
  id: '/organizer/$id',
  path: '/organizer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronMaintenanceRoute =
  ApiPublicCronMaintenanceRouteImport.update({
    id: '/api/public/cron/maintenance',
    path: '/api/public/cron/maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/legal': typeof LegalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/host': typeof AuthenticatedHostRoute
  '/my-games': typeof AuthenticatedMyGamesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/activity/$id': typeof ActivityIdRoute
  '/organizer/$id': typeof OrganizerIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/cron/maintenance': typeof ApiPublicCronMaintenanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/legal': typeof LegalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/host': typeof AuthenticatedHostRoute
  '/my-games': typeof AuthenticatedMyGamesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/activity/$id': typeof ActivityIdRoute
  '/organizer/$id': typeof OrganizerIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/cron/maintenance': typeof ApiPublicCronMaintenanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/legal': typeof LegalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/host': typeof AuthenticatedHostRoute
  '/_authenticated/my-games': typeof AuthenticatedMyGamesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/activity/$id': typeof ActivityIdRoute
  '/organizer/$id': typeof OrganizerIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/cron/maintenance': typeof ApiPublicCronMaintenanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/join'
    | '/legal'
    | '/reset-password'
    | '/admin'
    | '/host'
    | '/my-games'
    | '/profile'
    | '/activity/$id'
    | '/organizer/$id'
    | '/api/public/health'
    | '/api/public/cron/maintenance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/join'
    | '/legal'
    | '/reset-password'
    | '/admin'
    | '/host'
    | '/my-games'
    | '/profile'
    | '/activity/$id'
    | '/organizer/$id'
    | '/api/public/health'
    | '/api/public/cron/maintenance'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/join'
    | '/legal'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/host'
    | '/_authenticated/my-games'
    | '/_authenticated/profile'
    | '/activity/$id'
    | '/organizer/$id'
    | '/api/public/health'
    | '/api/public/cron/maintenance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  JoinRoute: typeof JoinRoute
  LegalRoute: typeof LegalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ActivityIdRoute: typeof ActivityIdRoute
  OrganizerIdRoute: typeof OrganizerIdRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicCronMaintenanceRoute: typeof ApiPublicCronMaintenanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/host': {
      id: '/_authenticated/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof AuthenticatedHostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-games': {
      id: '/_authenticated/my-games'
      path: '/my-games'
      fullPath: '/my-games'
      preLoaderRoute: typeof AuthenticatedMyGamesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/activity/$id': {
      id: '/activity/$id'
      path: '/activity/$id'
      fullPath: '/activity/$id'
      preLoaderRoute: typeof ActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/$id': {
      id: '/organizer/$id'
      path: '/organizer/$id'
      fullPath: '/organizer/$id'
      preLoaderRoute: typeof OrganizerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/maintenance': {
      id: '/api/public/cron/maintenance'
      path: '/api/public/cron/maintenance'
      fullPath: '/api/public/cron/maintenance'
      preLoaderRoute: typeof ApiPublicCronMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedHostRoute: typeof AuthenticatedHostRoute
  AuthenticatedMyGamesRoute: typeof AuthenticatedMyGamesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedHostRoute: AuthenticatedHostRoute,
  AuthenticatedMyGamesRoute: AuthenticatedMyGamesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  JoinRoute: JoinRoute,
  LegalRoute: LegalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ActivityIdRoute: ActivityIdRoute,
  OrganizerIdRoute: OrganizerIdRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicCronMaintenanceRoute: ApiPublicCronMaintenanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
