REVOKE ALL ON FUNCTION public.set_updated_at() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sync_activity_counts() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.guard_activity_capacity() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.log_payment_status_change() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.recalc_user_rating() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_admin() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_activity_host(uuid, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_activity_host(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_updated_at() TO service_role;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO service_role;
GRANT EXECUTE ON FUNCTION public.sync_activity_counts() TO service_role;
GRANT EXECUTE ON FUNCTION public.guard_activity_capacity() TO service_role;
GRANT EXECUTE ON FUNCTION public.log_payment_status_change() TO service_role;
GRANT EXECUTE ON FUNCTION public.recalc_user_rating() TO service_role;